

Application:
  Width: 1024
  Height: 768

Optional:
  PassInfoUI: false

Scene:
  ScenePath: Assets/single
  SceneName: bunny
  SceneType: singleModel # singleModel, multiModel
  RepeatScene: [4,4,4] # 重复场景次数
  LightPassLoop: 1
  PostProcessLoop: 1

Environment:
  LightPosition: 0, 0, 0
